apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ESMS
  description: ESMS Team
spec:
  type: team
  profile:
    displayName: ESMS
    email: ESMS@sample.com.my
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Bailey&backgroundType=gradientLinear&backgroundColor=b6e3f4,ffd5dc,ffdfbf,c0aede
  parent: maxisorg
  children: []
