apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: SEND_SMS_NON_MAXIS_ESMS
  descriprion: ESMS SMS (NON MAXIS MOBILE NUMBER)
  annotations:
    backstage.io/source-template: template:default/springboot-template
    backstage.io/linguist: 'https://github.com/backstage/backstage/tree/master/plugins/playlist'
spec:
  type: service
  lifecycle: production
  owner: ESMS
  providesApis:
    - SEND_SMS_NON_MAXIS
