apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: HERO
  description: HERO Team
spec:
  type: team
  profile:
    displayName: HERO
    email: HERO@sample.com.my
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Bailey&backgroundType=gradientLinear&backgroundColor=b6e3f4,ffd5dc,ffdfbf,c0aede
  parent: maxisorg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: SMS_TAC
  descriprion: HERO SMS TAC
  annotations:
    backstage.io/source-template: template:default/springboot-template
    backstage.io/linguist: 'https://github.com/backstage/backstage/tree/master/plugins/playlist'
spec:
  type: service
  lifecycle: production
  owner: HERO
  providesApis:
    - SMS_TAC_HERO
  consumesApis:
    - SEND_SMS_ONLINE
