apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Gitlab_API
  description: The Gitlab API
  tags:
    - spotify
    - rest
  annotations:
    # The annotation is deprecated, we use placeholders (see below) instead, remove it later.
    backstage.io/definition-at-location: 'url:https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/spotify.com/v1/swagger.yaml'
spec:
  type: openapi
  lifecycle: production
  owner: TSP
  definition:
    $text: https://github.com/iamkum123/SwaggerFileHub/blob/main/gitlabAPI.yaml
    #https://github.com/APIs-guru/openapi-directory/blob/dab6854d4d599aafb0eb36e6c7ae1fe0c37509b7/APIs/spotify.com/2021.4.2/openapi.yaml
