apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: TSP
  description: Telesales Team
spec:
  type: team
  profile:
    displayName: TSP
    email: GRP_ISD_TSP@maxis.com.my
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Bailey&backgroundType=gradientLinear&backgroundColor=b6e3f4,ffd5dc,ffdfbf,c0aede
  parent: Maxis Corp
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Omnichannel
  description: Omnichannel
  tags:
    - tsp
    - omnichannel
    - order
  annotations:
    backstage.io/linguist: 'https://github.com/backstage/backstage/tree/master/plugins/playlist'
spec:
  type: service
  lifecycle: production
  owner: TSP
  providesApis:
    - SMS 
  consumesApis:
    - SEND_SMS_ONLINE
